language: python

notifications:
  email: false

# Setup anaconda
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - hash -r
  # - conda update -q conda
  # Useful for debugging any issues with con
  - conda info -a
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv


  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  -
  - conda install --yes anaconda-client
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy nose dateutil pandas statsmodels h5py
  - pip install coveralls
  - pip install linop
  - pip install healpy
  - pip install krypy 
  - ./setup.sh

# Run test
script:
   - nosetests -v --cover-package=interfaces --cover-package=utilities tests
#  - nosetests --with-coverage --cover-package=interfaces --cover-package=utilities tests

# Calculate coverage
#after_success:
#  - coveralls --config_file .coveragerc
