language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

notifications:
  email: false
 
# Setup anaconda
before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
  	wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
	get https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - hash -r 
  - conda update -q conda
  # Useful for debugging any issues with con
  - conda info -a
  - conda create --yes -n condaenv python=$TRAVIS_PYTHON_VERSION
  - conda install --yes -n condaenv pip
  - source activate condaenv
   
  
  # The next couple lines fix a crash with multiprocessing on Travis and are not specific to using Miniconda
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
# Install packages
install:
  - 
  - conda install --yes anaconda-client
  - conda install --yes python=$TRAVIS_PYTHON_VERSION atlas numpy scipy nose dateutil pandas statsmodels
  - pip install coveralls
  - pip install linop
  - ./setup.sh
 
# Run test
script:
   - nosetests --cover-package=interfaces --cover-package=utilities tests
#  - nosetests --with-coverage --cover-package=interfaces --cover-package=utilities tests
 
# Calculate coverage
#after_success:
#  - coveralls --config_file .coveragerc
